#!/bin/bash
# Author: casheywen@qq.com

if [[ $# -lt 3 ]]
then
    echo "Usage: $0 ipfile src_path dst_path"
    exit
fi

MACHINE_LIST="$1"
SRC_PATH="$2"
DST_PATH="$3"
TMP="/tmp/pull${RANDOM}"

read IP USER PASSWORD PORT < "${MACHINE_LIST}"

if [[ ${?} -ne 0 || -z "${PORT}" ]]
then
    echo "${0}: ${MACHINE_LIST} does not exist or format error" >&2
    exit 1
fi

cat << EOF > "${TMP}"
set timeout 8
spawn -noecho scp -P${PORT} -r "${USER}@${IP}:${SRC_PATH}" "${DST_PATH}"
while (1) {
    expect  {
        "yes/no)?" { send "yes\r";puts "yes" }
        "assword:" { send "${PASSWORD}\r"; break }
        timeout  { puts "${IP} time out" ;exit 2; break }
    }
}

expect eof

catch wait result
exit [lindex \$result 3]

EOF

expect "${TMP}"
RET=$?

rm "${TMP}"

exit ${RET}
